# Generated by Django 3.2.3 on 2021-06-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_guide', '0019_delete_book'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(related_name='autors', to='book_guide.Author', verbose_name='Автор'),
        ),
    ]
