# Generated by Django 3.2.3 on 2021-06-20 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_guide', '0019_delete_book'),
        ('books', '0002_auto_20210620_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='autors', to='book_guide.author', verbose_name='Автор'),
            preserve_default=False,
        ),
    ]
