# Generated by Django 3.2.3 on 2021-06-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20210620_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Название книги'),
        ),
    ]
