# Generated by Django 3.2.3 on 2021-06-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='рейтинг (0 - 10)'),
        ),
    ]
