# Generated by Django 3.2.3 on 2021-07-13 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_rating'),
        ('carts', '0004_alter_booksincart_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksincart',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.book', verbose_name='Book'),
        ),
    ]
