# Generated by Django 3.2.3 on 2021-06-24 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_booksincart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='customer',
        ),
        migrations.DeleteModel(
            name='BooksInCart',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
