# Generated by Django 3.2.3 on 2021-06-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210629_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tel',
            field=models.CharField(default=1, max_length=15, verbose_name='Tel number'),
            preserve_default=False,
        ),
    ]
