# Generated by Django 3.2.3 on 2021-06-29 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='another_info',
            field=models.CharField(blank=True, max_length=100, verbose_name='Дополнительная информация'),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='profile',
            name='home_adress',
            field=models.CharField(blank=True, max_length=50, verbose_name='Домашний дрес'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_group',
            field=models.CharField(default='none', max_length=25, verbose_name='Группа'),
        ),
    ]
