# Generated by Django 3.2.3 on 2021-07-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210630_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default=1, max_length=20, verbose_name='город'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(default=1, max_length=20, verbose_name='страна'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='home_index',
            field=models.IntegerField(default=11234567, verbose_name='индекс'),
            preserve_default=False,
        ),
    ]
