# Generated by Django 3.2.3 on 2021-07-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210706_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_group',
        ),
        migrations.AddField(
            model_name='profile',
            name='group',
            field=models.CharField(default='none', max_length=25, verbose_name='Группа'),
        ),
    ]
