# Generated by Django 3.2.3 on 2021-05-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_guide', '0004_publisher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название книги')),
                ('price', models.FloatField(verbose_name='Цена (BYN)')),
                ('publication_date', models.DateTimeField(auto_now_add=True, verbose_name='Год издания')),
            ],
        ),
    ]
