# Generated by Django 3.2.3 on 2021-05-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_guide', '0005_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='age_restrictions',
            field=models.BooleanField(default=False, verbose_name='возрастные ограничения'),
        ),
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.IntegerField(default=0, verbose_name='Количество страниц'),
            preserve_default=False,
        ),
    ]
