# Generated by Django 3.2.3 on 2021-05-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_guide', '0006_auto_20210523_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='active',
            field=models.BooleanField(default=False, verbose_name='доступен для заказа, ДА/Нет'),
        ),
        migrations.AddField(
            model_name='book',
            name='quantity_on_hand',
            field=models.IntegerField(default=0, verbose_name='количество книг в наличии'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='рейтинг (0 - 10)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.IntegerField(default=0, verbose_name='Количество страниц'),
        ),
    ]
