# Generated by Django 3.2.3 on 2021-05-23 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_guide', '0007_auto_20210523_1222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Книгу', 'verbose_name_plural': 'Книги'},
        ),
    ]
