# Generated by Django 3.2.3 on 2021-05-23 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_guide', '0009_auto_20210523_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='book_guide.author'),
            preserve_default=False,
        ),
    ]
