# Generated by Django 3.2.3 on 2021-05-23 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_guide', '0011_alter_book_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='line',
            options={'verbose_name': 'Серия', 'verbose_name_plural': 'Серия'},
        ),
        migrations.AddField(
            model_name='book',
            name='line',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='book_guide.line', verbose_name='Серия'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='line',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Серия'),
        ),
    ]
