# Generated by Django 3.2.3 on 2021-05-23 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_guide', '0013_auto_20210523_1750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='line',
            options={'verbose_name': 'Серия', 'verbose_name_plural': 'Серии'},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'verbose_name': 'Издатель', 'verbose_name_plural': 'Издатели'},
        ),
    ]
