# Generated by Django 3.2.3 on 2021-05-23 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_guide', '0014_auto_20210523_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='book_guide.genre', verbose_name='Жанр'),
            preserve_default=False,
        ),
    ]
