# Generated by Django 3.2.3 on 2021-05-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_guide', '0016_alter_book_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='рейтинг (0 - 10)'),
        ),
        migrations.AlterField(
            model_name='line',
            name='name',
            field=models.CharField(blank=True, default=1, max_length=50, verbose_name='Серия'),
            preserve_default=False,
        ),
    ]
