# Generated by Django 3.2.3 on 2021-06-10 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_guide', '0018_book_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
