# Generated by Django 3.2.3 on 2021-07-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tel',
            field=models.TextField(default=375291234567, verbose_name='tel'),
            preserve_default=False,
        ),
    ]
