# Generated by Django 3.2.3 on 2021-07-04 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_tel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tel',
        ),
    ]
